### ISSUE TITLE
Mod version 1.0.1 lists 1.20.1 as supported on Modrinth, but fails to load 

### ISSUE THREAD

**Issue by ArchOwlen** [Gitko01/BelowBedrockCaves#1]
![image](https://github.com/Gitko01/BelowBedrockCaves/assets/69368336/f6e12243-a044-4e20-a421-83801a99bc43)
(Using Quilt, not Fabric)

Attempting to manually adjust and build from source, but I don't know mod creation that well (yet), so I have been unsuccessful so far

**Comment by ArchOwlen** [comment]
I'm dumb
Grabbed the 1.0.0 1.20.1 version of the mod on github and it works fine

Not sure what was changed in the portalAPI, if it would be worth making a backport

**Comment by ChacePratt** [comment]
I believe you loaded the 1.0.0-1.19.2 version instead of the 1.0.1-1.20.1 version originally based off of the file name in the screenshot you sent

**Comment by ArchOwlen** [comment]
My mistake, didn't realize that

It may need to be adjusted on Modrinth though, as PrismMC (thus, also Modrinth) grabs that one for 1.20.1 for some reason

**Comment by ChacePratt** [comment]
Ah - I think I figured out what I did wrong on Modrinth. I'll go ahead and fix everything.
